### ISSUE TITLE
Issue with loading Beslistabellen when following the installment path of Valtimo noted in the Valtimo Academy

### ISSUE THREAD

**Issue by Damon-Ritense** [valtimo-platform/valtimo-issues#6]
## Expected behavior
When installing valtimo-docker-compose and running it on Docker Desktop I expect to have all functionalities shown in Valtimo available to me.

## Current behavior
When opening Beslistabellen, I get an error message (403 type) and the page just keeps loading.
![image](https://github.com/user-attachments/assets/f23512da-8534-462c-8fa5-2eefd15cd949)

## Possible solution (optional)
I haven't a clue :(

## Steps to reproduce
*Provide an unambiguous set of steps to reproduce this bug.*
*Include code to reproduce, if relevant*
1. Follow the install guide from the Valtimo Academy UI welcome path: https://academy.valtimo.nl/courses/introductietraining-voor-business-process-engineers-ui-versie-v12
2. Run Valtimo on Docker Desktop
3. Try and open Beslistabellen

**Comment by ThomasMinkeRitense** [comment]
Solution: added a CORS property to the docker compose file.
